### ISSUE TITLE
Potential false positive or confusing/inconsistent report.

### ISSUE THREAD

**Issue by shurcooL** [mvdan/unparam#13]
Using latest versions of everything, Go 1.9rc1 on latest macOS.

```
$ unparam github.com/shurcooL/home
users.go:79:19: ctx is unused
```

This is where it refers to:

```Go
func (Users) Edit(ctx context.Context, er users.EditRequest) (users.User, error) {
	return users.User{}, errors.New("Edit is not implemented")
}
```

Which is fine, `ctx` is indeed unused and I have no problems doing this:

```Go
func (Users) Edit(_ context.Context, er users.EditRequest) (users.User, error) {
	return users.User{}, errors.New("Edit is not implemented")
}
```

However, it's a bit surprising/inconsistent in that `er` is also unused, yet there is no report for that. How come?

Also, the README says:

> To minimise false positives, it ignores:
>
> * Unnamed and underscore parameters
> * Funcs whose signature matches a reachable func type
> * Funcs whose signature matches a reachable interface method
> * Funcs that have empty bodies
> * Funcs that will almost immediately panic or return constants

This is obviously an unimplemented method that returns an error right away. Shouldn't it be ignored because of "Funcs that will almost immediately panic or return constants"? Or not, because it returns `errors.New`, which isn't a constant?

It's completely possible everything is working as intended and there is no problem, but I wanted to report this on the off chance something here is unintentional. If things are working as expected, perhaps you can clarify which clause explains this behavior.

**Comment by mvdan** [comment]
> However, it's a bit surprising/inconsistent in that er is also unused, yet there is no report for that. How come?

Honestly, good question. I have no idea. Let me get back to you after some debugging.

> Shouldn't it be ignored because of "Funcs that will almost immediately panic or return constants"?

Yes. The way this was done was by adding more and more test cases, and playing the SSA dance to see what nodes I should be whitelisting. If I allow too much, like branches, false positives show up. But I also want to allow stuff like converting specific types to interfaces, as that's very common with `error`.

So yeah, this probably needs a bit of tweaking. Thanks for reporting!

**Comment by mvdan** [comment]
> Let me get back to you after some debugging.

So it turns out that here:

`func (Foo) Bar(unused int) { ... }`

We skip `unused` as the method function receiver. We should only be doing that for `f` in the following scenario:

`func (f Foo) Bar(...) {...}`

The reason the tool is getting confused is because I believe that `go/ssa` is breaking a godoc contract:

> If the function is a method (Signature.Recv() != nil) then the first element of Params is the receiver parameter.

And I have:

```
for i, par := range fn.Params {
        if i == 0 && fn.Signature.Recv() != nil { // receiver
                continue
        }
```

I'll debug some more, to confirm that this is actually a bug in go/ssa. But it certainly looks like it. Will likely end up submitting an issue and a CL.

**Comment by mvdan** [comment]
Ignore the entirety of the comment above - I'm jetlagged and completely wrong.

**Comment by mvdan** [comment]
So it turns out that unused struct parameters were broken, because ssa was for some reason inserting a store that used the parameter even if the parameter wasn't used at all in the function body. And we were treating that as a real use of the parameter.

I've made a fix, and now it shows both:

```
users.go:79:19: ctx is unused
users.go:79:40: er is unused
```

This also makes it show a lot of other stuff, and there are other things to fix. But this particular one is fixed for now :)

**Comment by mvdan** [comment]
@shurcooL after two more fixes (see master), that package now has zero unused parameters. Thanks again for reporting the issues!

The issue is, however, that people tend to file issues for false positives but not for false negatives, so the SSA heuristic must be leaning too much towards being conservative. If you find any unused parameters it didn't flag, please do say so :)

**Comment by shurcooL** [comment]
Will do. Thanks a lot!

Just checking, is the reason both `ctx` and `er` are skipped now because of this clause?

> - Funcs that will almost immediately panic or return constants

If so, I think you should correct that to also include "or return errors" or something. Because `errors.New("Edit is not implemented")` is not a constant.

**Comment by shurcooL** [comment]
> people tend to file issues for false positives but not for false negatives

I think you'll need to make it much more precise what's being ignored in the README to be able to report false negatives.

You might want to consider a flag `-all` or `-v` or something that disables all the "skips", and prints the _reason_ they'd be skipped. Something like this:

```
$ unparam -v github.com/shurcooL/home
users.go:79:19: ctx is unused (ignored because in a dummy implementation)
users.go:79:40: er is unused (ignored because in a dummy implementation)
some.go:123:45: x is unused (ignored because matches a reachable interface method http.Handler)
```

(That could be a lot of work.)

**Comment by mvdan** [comment]
> If so, I think you should correct that to also include "or return errors" or something. Because `errors.New("Edit is not implemented")` is not a constant.

Yeah - I need to reword that, and perhaps other parts of the README too. The heuristics have been changing over time.

> prints the reason they'd be ignored normally

I actually thought of something similar, and less complicated to implement, which is already in master for my debugging purposes:

```
 $ unparam -debug
func (github.com/mvdan/unparam/check.byNamePos).Swap
  skip - type is required via call
func github.com/mvdan/unparam/check.insertedStore
parameter instr : golang.org/x/tools/go/ssa.Instruction
  skip - used somewhere in the func body
```

This debug mode gives info on *all* funcs and parameters however, not just the ones that seem to be unused but are ignored.

You're right that your idea would be more work, but it would also be more user-friendly. I'll think about it and play with it at some point.
