### ISSUE TITLE
Don't consider the blank identifier as having a name.

### ISSUE THREAD

**Issue by shurcooL** [mvdan/unparam#25]
Results that are named after blank identifier are currently considered as "having a name", but in reality, they should be treated as not having a name. The `_` name is not descriptive, and there can be more than 1 of them.

### Got

```
foobar - result _ is always nil
```

### Expected

```
foobar - result 1 (error) is always nil
```

## Cause

https://github.com/mvdan/unparam/blob/0c3aec22d8e6d9b51a978b31539c51fd52071488/check/check.go#L665-L671

I believe that code should be changed:

```diff
func paramDesc(i int, v *types.Var) string {
	name := v.Name()
-	if name != "" {
+	if name != "" && name != "_" {
		return name
	}
	return fmt.Sprintf("%d (%s)", i, v.Type().String())
}
```

**Comment by mvdan** [comment]
Care to send a patch with a simple test?

**Comment by shurcooL** [comment]
No problem. Should I address https://github.com/mvdan/unparam/commit/48c05434e287d42eb36fcccb260615c189e8f391#r27942090 as part of it?

**Comment by mvdan** [comment]
I'm actually wondering if we should skip these. We do it for receiving parameters, like:

```
func UnusedParam(_ int, bool) {
    ...
}
```

Both parameters are skipped in that case. I think my reasoning was that explicitly making them unnamed meant that the user *really* wanted them there. And I think the same didn't occur to me for result parameters because they are very often unnamed - but I didn't consider the underscore name.

In any case, this is a step in the right direction, so I'll merge.

**Comment by mvdan** [comment]
@shurcooL did you find any examples of this occurrence that were correct warnings?

**Comment by shurcooL** [comment]
Yes, I did.
