### ISSUE TITLE
implement using honnef.co/go/tools/lint

### ISSUE THREAD

**Issue by tamird** [mvdan/unparam#4]
This would be helpful for users like CockroachDB's metacheck: https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/metacheck/main.go which wants to run many checks without having to load the program more than once.

**Comment by mvdan** [comment]
Thanks for opening this issue!

I believe @dominikh's `lint` package is for internal use only, as in its API is not stable nor versioned. I've suggested that he make it an internal package in the past, but I guess he hasn't made a choice yet.

As for a way to run multiple linters in a single pass - I completely agree with you. Tools like `gometalinter` take forever, especially if the SSA work is not reused. But I think the way forward is for linters to have an importable package that satisfies an interface, like `Check(*ssa.Program) []Warning`. That way, it won't be tied to any one library like `honnef.co/go/tools/lint`.

Also note that Dominik's ssa packages are forks with changes; I use the vanilla `golang.org/x` packages. I'm not sure what his changes are, but it's not safe to assume that my linter would work fine (or even compile) with his SSA packages.

By the way, I opened a similar issue here: https://github.com/dominikh/go-tools/issues/39 - But that one is just related to Dominik's tools, not for every linter that uses any combination of `go/ast`, `go/types` and `ssa`.

**Comment by mvdan** [comment]
I've developed my interface idea some more here: https://github.com/mvdan/unparam/issues/5

**Comment by mvdan** [comment]
And the first implementation: https://github.com/mvdan/lint

Not very useful since it's only the one linter now, and things aren't stable yet. But this should end up doing what you're after.

As for Dominik's tools, I believe they could be included in `metalint` fairly easily if he switches back to `golang.org/x/tools/go/...`. I'm afraid there is not much I can do about running his linters and all the rest if the underlying `ssa` packages are different.

**Comment by tamird** [comment]
Nice, thanks for picking this up so eagerly. Just going to cc @dominikh in case he hasn't seen this.
