### ISSUE TITLE
Ignoring leading underscore _parameters

### ISSUE THREAD

**Issue by jpalardy** [mvdan/unparam#42]
In [Elixir](https://hexdocs.pm/elixir/master/naming-conventions.html#underscore-_foo) and [Rust](https://stackoverflow.com/questions/48361537/why-do-underscore-prefixed-variables-exist), variable names prefixed with an underscore are meant to flag unused variables. In fact, not using the underscore is considered an error by the compiler

The advantage is documentation: still giving a name to what's received while also flagging it as unused.

Similar to #35, an easy way to quiet unparam would be:

```golang
func run(cmd *cobra.Command, _args []string) {
  cmd.Usage()
}
```

What's your take on this?

**Comment by ainar-g** [comment]
<p>
I thought that <code>golint</code> will complain about such names, but
it doesn't.  Huh.  Interesting.
</p>

**Comment by mvdan** [comment]
If the argument can't be removed, didn't the fix for #35 cover your case here? Could you provide me with a way to reproduce the warning when the parameter can't be removed?

I'm hesitant to start understanding that a leading underscore means "the parameter is unused and that's okay". This was fine for `_`, because that has a meaning in Go; one can do `var _ = "foo"` and the compiler won't complain that the variable is unused.

I worry that if we add this logic, users of unparam will start abusing this pattern to simply make the tool shut up, turning their code non-idiomatic. As I understand it, this pattern is not widespread or recommended for Go. I don't want the tool to try to encourage a pattern that isn't common.

**Comment by jpalardy** [comment]
It's part of an application template I'm using at work:

```go
var serveCmd = &cobra.Command{
    Use:   "serve",
    Short: "…",
    Run:   runServeCmd,
}

func runServeCmd(cmd *cobra.Command, args []string) {
    app := newFXApp(cmd, args)
    app.Run()
}

// in other file

func newFXApp(cmd *cobra.Command, _ []string) *fx.App {
    // in this case, the 2nd argument isn't used, but that might always be the case…
    return fx.New(
        fx.Provide(// ... more irrelevant code
```

**Comment by jpalardy** [comment]
so the linter complains, and people turn off the linter :-(

(instead of simplifying this code)

**Comment by mvdan** [comment]
The warning in this case would be for `newFXApp`'s second argument?

**Comment by jpalardy** [comment]
that's right, it was originally `args`, but I changed it to `_` for unparam

**Comment by mvdan** [comment]
To make sure I completely follow - why do you want to keep the parameter there? For consistency with `runServeCmd`, or because it might be used in the future?

I'd personally just not use the parameter. If there is a good reason to keep the parameter there, I'd like to teach `unparam` how to recognise that. That would be better than giving the human more ways to work around the tool doing its job :)

**Comment by jpalardy** [comment]
>  For consistency with runServeCmd, or because it might be used in the future?

for both reasons 😃 

It's part of a template, so removing the parameters might bring up more questions (why is the signature different?) than leaving it unused.

And if the args are needed in the future, I would have to follow the call chain in reverse and modify the signatures.

I understand that it's not necessarily the "Go way"

**Comment by mvdan** [comment]
> I understand that it's not necessarily the "Go way"

Yeah, this is the problem here, in my opinion. I don't want to teach the tool a way to work around what it's meant to do, especially not when it's not common at all in existing Go code.

From what you've said above, the tool is correct in pointing out these parameters as unused. If you can show me a way to teach it that they are not, which isn't a workaround, I'm happy to investigate if it would be possible to do.

As for your current alternatives, I think you should look into ways to make the parameters actually required. For example:

* Make your function satisfy a function type explicitly, like `var _ templateFunc = myFunc` above `func myFunc(...) { ... }`
* Make your function satisfy an interface as a method, similarly to the above
* Make the parameter used at the top of the body, like `_ = args // not used yet`
