### ISSUE TITLE
mvdan.cc certificate expired

### ISSUE THREAD

**Issue by piotrbulinski** [mvdan/unparam#45]
Seems like your certificate for mvdan.cc expired as of Tuesday, February 11, 2020 at 2:08:46 PM.
Can you please update it, so we can keep using your great packages for making better software? :)

**Comment by mvdan** [comment]
Sorry about the trouble. It's fixed now.

**Comment by ainar-g** [comment]
<p>
@piotrbulinski you probably already know that, but for any other
readers, you can vendor your tools together with your module's other
dependencies using the <code>tools.go</code> convention.  See
<a href="https://github.com/golang/go/wiki/Modules#how-can-i-track-tool-dependencies-for-a-module">this quesion in the modules FAQ</a>
</p>

**Comment by mvdan** [comment]
Yep. Please don't depend on my site being up 24/7, because I'm a human that sleeps and pays for the server out of pocket. I don't have the money or time to spare to set up 99.9999% availability.

Also, since Go 1.13, proxy.golang.org is a default. So if you pin a version via `go.mod`, you should be able to download that version from the proxy, which is guaranteed to be up more often.
